"""
常量定义
"""
from typing import Literal

# ========== 常量 ==========
RUN_ID_PREFIX = "RUN"
RUN_TS_FORMAT = "%Y%m%d_%H%M%S"     # UTC 时间戳格式
RUN_ID_FORMAT = f"{RUN_ID_PREFIX}_{{ts}}_UTC"  # 例如: RUN_20251109_143012_UTC

CSV_ENCODING = "utf-8"              # 无 BOM
CSV_LINE_TERMINATOR = "\n"
CSV_DELIMITER = ","

# 输出目录布局（相对 RUN 根目录）
DIR_CSV = "csv"
DIR_LOGS = "logs"
DIR_ARTIFACTS = "artifacts"

# 文件名非法字符
INVALID_FILENAME_CHARS = r'\/:*?"<>|'

# 默认配置值
DEFAULT_MIN_BLOCK_HEIGHT = 3
DEFAULT_MIN_BLOCK_WIDTH = 3
DEFAULT_HOLE_TOLERANCE_ROWS = 1
DEFAULT_HOLE_TOLERANCE_COLS = 1
DEFAULT_DENSITY_THRESHOLD = 0.35
DEFAULT_RECTANGULARITY_THRESHOLD = 0.8
DEFAULT_MDL_WEIGHTS = (0.6, 0.3, 0.1)  # α, β, γ
DEFAULT_MERGE_GAIN_THRESHOLD = 0.5
DEFAULT_MAX_HEADER_ROWS = 6
DEFAULT_HEADER_STYLE_WEIGHT = 0.6
DEFAULT_DUPLICATE_COL_SUFFIX = "_dup{n}"

